openapi: 3.0.3
info:
  title: prism mockの動作確認用API
  description: 「npx prism mock docs\openapi.yml」で起動し、openapi.httpで動作確認する
  version: 1.0.0

#
# サーバー設定
#
servers:
  - url: http://localhost:4010/
    description: local

#
# パス（エンドポイント）定義
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#paths-object
#
paths:
  /weather/points:
    get:
      summary: 観測地点リストの取得
      description: 観測地点のリストを取得する
      responses:
        "200":
          description: 観測地点のリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ObservationPoint"
              examples:
                noneCase:
                  summary: "観測地点"
                  value:
                    [
                      {
                        "name": "東京",
                        "latitude": 35.682839,
                        "longitude": 139.759455,
                      },
                      {
                        "name": "大阪",
                        "latitude": 34.693737,
                        "longitude": 135.502167,
                      },
                      {
                        "name": "札幌",
                        "latitude": 43.062096,
                        "longitude": 141.354376,
                      },
                      {
                        "name": "福岡",
                        "latitude": 33.590355,
                        "longitude": 130.401716,
                      },
                      {
                        "name": "名古屋",
                        "latitude": 35.181450,
                        "longitude": 136.906557,
                      },
                      {
                        "name": "仙台",
                        "latitude": 38.268215,
                        "longitude": 140.869356,
                      },
                      {
                        "name": "広島",
                        "latitude": 34.385203,
                        "longitude": 132.455293,
                      },
                      {
                        "name": "那覇",
                        "latitude": 26.212401,
                        "longitude": 127.680932,
                      },
                      {
                        "name": "新潟",
                        "latitude": 37.916192,
                        "longitude": 139.036412,
                      },
                      {
                        "name": "金沢",
                        "latitude": 36.561325,
                        "longitude": 136.656205,
                      },
                      {
                        "name": "熊本",
                        "latitude": 32.803103,
                        "longitude": 130.707891,
                      },
                      {
                        "name": "松山",
                        "latitude": 33.841645,
                        "longitude": 132.765681,
                      },
                      {
                        "name": "高知",
                        "latitude": 33.559706,
                        "longitude": 133.531079,
                      },
                      {
                        "name": "鹿児島",
                        "latitude": 31.596553,
                        "longitude": 130.557115,
                      },
                      {
                        "name": "長野",
                        "latitude": 36.648583,
                        "longitude": 138.194770,
                      },
                      {
                        "name": "岡山",
                        "latitude": 34.655145,
                        "longitude": 133.919502,
                      },
                    ]

#
# 共通定義
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#components-object
#
components:
  # 再利用可能なスキーマ(データモデル)定義
  schemas:
    ObservationPoint:
      type: object
      properties:
        name:
          type: string
          description: 観測地点名
        latitude:
          type: number
          description: 緯度
        longitude:
          type: number
          description: 経度
      required:
        - name
        - latitude
        - longitude
    Error:
      type: object
      properties:
        code:
          type: integer
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
      required:
        - code
        - message

tags:
  - name: "Users"
    description: "ユーザー関連のAPI"
